services:
  mysql-order:
    image: mysql:8.3.0
    container_name: mysqlOrderDB
    environment:
      MYSQL_ROOT_PASSWORD: nick123
      MYSQL_DATABASE: order_service
    ports:
      - "3306:3306"
    volumes:
      - ./orders/mysql:/var/lib/mysql

  mysql-manufacture:
    image: mysql:8.3.0
    container_name: mysqlManufactureDB
    environment:
      MYSQL_ROOT_PASSWORD: nick123
      MYSQL_DATABASE: manufacture_service
    ports:
      - "3307:3306"
    volumes:
      - ./manufacture/mysql:/var/lib/mysql

  mysql-logistics:
    image: mysql:8.3.0
    container_name: mysqlLogisticsDB
    environment:
      MYSQL_ROOT_PASSWORD: nick123
      MYSQL_DATABASE: logistics_service
    ports:
      - "3308:3306"
    volumes:
      - ./logistics/mysql:/var/lib/mysql

  mysql-sales:
    image: mysql:8.3.0
    container_name: mysqlSalesDB
    environment:
      MYSQL_ROOT_PASSWORD: nick123
      MYSQL_DATABASE: sales_service
    ports:
      - "3309:3306"
    volumes:
      - ./sales/mysql:/var/lib/mysql

  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    ports:
      - "9092:9092"
      - "29092:29092"
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://broker:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  kafka-ui:
    container_name: kafka-ui
    image: provectuslabs/kafka-ui:latest
    ports:
      - "8086:8080"
    depends_on:
      - broker
    environment:
      KAFKA_CLUSTERS_NAME: Factory
      KAFKA_CLUSTERS_BOOTSTRAPSERVERS: broker:29092
      DYNAMIC_CONFIG_ENABLED: 'true'

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    container_name: schema-registry
    depends_on:
      - broker
    ports:
      - "8095:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: broker:29092
      SCHEMA_REGISTRY_LISTENERS: http://schema-registry:8081