/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diploma.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class OrderListWrapper extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6510580763797139809L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"OrderListWrapper\",\"namespace\":\"com.diploma.avro\",\"fields\":[{\"name\":\"orders\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"OrderDTO\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"productId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"pricePerObject\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"locationId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"price\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"quantity\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"orderDate\",\"type\":[\"null\",{\"type\":\"int\",\"logicalType\":\"date\"}],\"default\":null},{\"name\":\"customerName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"OPEN\",\"IN_PRODUCTION\",\"DELIVERY\",\"DELIVERED\",\"SOLD\",\"RETURNED\"]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.DateConversion());
  }

  private static final BinaryMessageEncoder<OrderListWrapper> ENCODER =
      new BinaryMessageEncoder<OrderListWrapper>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<OrderListWrapper> DECODER =
      new BinaryMessageDecoder<OrderListWrapper>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<OrderListWrapper> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<OrderListWrapper> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<OrderListWrapper> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<OrderListWrapper>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this OrderListWrapper to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a OrderListWrapper from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a OrderListWrapper instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static OrderListWrapper fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<com.diploma.avro.OrderDTO> orders;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public OrderListWrapper() {}

  /**
   * All-args constructor.
   * @param orders The new value for orders
   */
  public OrderListWrapper(java.util.List<com.diploma.avro.OrderDTO> orders) {
    this.orders = orders;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return orders;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: orders = (java.util.List<com.diploma.avro.OrderDTO>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'orders' field.
   * @return The value of the 'orders' field.
   */
  public java.util.List<com.diploma.avro.OrderDTO> getOrders() {
    return orders;
  }


  /**
   * Sets the value of the 'orders' field.
   * @param value the value to set.
   */
  public void setOrders(java.util.List<com.diploma.avro.OrderDTO> value) {
    this.orders = value;
  }

  /**
   * Creates a new OrderListWrapper RecordBuilder.
   * @return A new OrderListWrapper RecordBuilder
   */
  public static com.diploma.avro.OrderListWrapper.Builder newBuilder() {
    return new com.diploma.avro.OrderListWrapper.Builder();
  }

  /**
   * Creates a new OrderListWrapper RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new OrderListWrapper RecordBuilder
   */
  public static com.diploma.avro.OrderListWrapper.Builder newBuilder(com.diploma.avro.OrderListWrapper.Builder other) {
    if (other == null) {
      return new com.diploma.avro.OrderListWrapper.Builder();
    } else {
      return new com.diploma.avro.OrderListWrapper.Builder(other);
    }
  }

  /**
   * Creates a new OrderListWrapper RecordBuilder by copying an existing OrderListWrapper instance.
   * @param other The existing instance to copy.
   * @return A new OrderListWrapper RecordBuilder
   */
  public static com.diploma.avro.OrderListWrapper.Builder newBuilder(com.diploma.avro.OrderListWrapper other) {
    if (other == null) {
      return new com.diploma.avro.OrderListWrapper.Builder();
    } else {
      return new com.diploma.avro.OrderListWrapper.Builder(other);
    }
  }

  /**
   * RecordBuilder for OrderListWrapper instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<OrderListWrapper>
    implements org.apache.avro.data.RecordBuilder<OrderListWrapper> {

    private java.util.List<com.diploma.avro.OrderDTO> orders;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diploma.avro.OrderListWrapper.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.orders)) {
        this.orders = data().deepCopy(fields()[0].schema(), other.orders);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing OrderListWrapper instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diploma.avro.OrderListWrapper other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.orders)) {
        this.orders = data().deepCopy(fields()[0].schema(), other.orders);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'orders' field.
      * @return The value.
      */
    public java.util.List<com.diploma.avro.OrderDTO> getOrders() {
      return orders;
    }


    /**
      * Sets the value of the 'orders' field.
      * @param value The value of 'orders'.
      * @return This builder.
      */
    public com.diploma.avro.OrderListWrapper.Builder setOrders(java.util.List<com.diploma.avro.OrderDTO> value) {
      validate(fields()[0], value);
      this.orders = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'orders' field has been set.
      * @return True if the 'orders' field has been set, false otherwise.
      */
    public boolean hasOrders() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'orders' field.
      * @return This builder.
      */
    public com.diploma.avro.OrderListWrapper.Builder clearOrders() {
      orders = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public OrderListWrapper build() {
      try {
        OrderListWrapper record = new OrderListWrapper();
        record.orders = fieldSetFlags()[0] ? this.orders : (java.util.List<com.diploma.avro.OrderDTO>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<OrderListWrapper>
    WRITER$ = (org.apache.avro.io.DatumWriter<OrderListWrapper>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<OrderListWrapper>
    READER$ = (org.apache.avro.io.DatumReader<OrderListWrapper>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










