/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diploma.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LogisticsDTO extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = -4462449826342533573L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogisticsDTO\",\"namespace\":\"com.diploma.avro\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"productId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"locationId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"distanceToWarehouse\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"transportId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"carType\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"CarType\",\"symbols\":[\"CADDY\",\"CARGOVAN\",\"TRUCK\",\"TRAIN\"]}],\"default\":null},{\"name\":\"speed\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"loadVolume\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"quantity\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"customerName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"OPEN\",\"IN_PRODUCTION\",\"DELIVERY\",\"DELIVERED\",\"SOLD\",\"RETURNED\"]}},{\"name\":\"deliveryDuration\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"deliveryEndTime\",\"type\":[\"null\",{\"type\":\"long\",\"logicalType\":\"timestamp-millis\"}],\"default\":null}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();
static {
    MODEL$.addLogicalTypeConversion(new org.apache.avro.data.TimeConversions.TimestampMillisConversion());
  }

  private static final BinaryMessageEncoder<LogisticsDTO> ENCODER =
      new BinaryMessageEncoder<LogisticsDTO>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogisticsDTO> DECODER =
      new BinaryMessageDecoder<LogisticsDTO>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LogisticsDTO> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LogisticsDTO> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LogisticsDTO> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LogisticsDTO>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LogisticsDTO to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LogisticsDTO from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LogisticsDTO instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LogisticsDTO fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.lang.Long id;
   private java.lang.Long productId;
   private java.lang.CharSequence name;
   private java.lang.CharSequence brand;
   private java.lang.CharSequence model;
   private java.lang.Long locationId;
   private java.lang.CharSequence city;
   private java.lang.CharSequence country;
   private java.lang.Long distanceToWarehouse;
   private java.lang.Long transportId;
   private com.diploma.avro.CarType carType;
   private java.lang.Long speed;
   private java.lang.Long loadVolume;
   private java.lang.Integer quantity;
   private java.lang.CharSequence customerName;
   private com.diploma.avro.OrderStatus status;
   private java.lang.CharSequence deliveryDuration;
   private java.time.Instant deliveryEndTime;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogisticsDTO() {}

  /**
   * All-args constructor.
   * @param id The new value for id
   * @param productId The new value for productId
   * @param name The new value for name
   * @param brand The new value for brand
   * @param model The new value for model
   * @param locationId The new value for locationId
   * @param city The new value for city
   * @param country The new value for country
   * @param distanceToWarehouse The new value for distanceToWarehouse
   * @param transportId The new value for transportId
   * @param carType The new value for carType
   * @param speed The new value for speed
   * @param loadVolume The new value for loadVolume
   * @param quantity The new value for quantity
   * @param customerName The new value for customerName
   * @param status The new value for status
   * @param deliveryDuration The new value for deliveryDuration
   * @param deliveryEndTime The new value for deliveryEndTime
   */
  public LogisticsDTO(java.lang.Long id, java.lang.Long productId, java.lang.CharSequence name, java.lang.CharSequence brand, java.lang.CharSequence model, java.lang.Long locationId, java.lang.CharSequence city, java.lang.CharSequence country, java.lang.Long distanceToWarehouse, java.lang.Long transportId, com.diploma.avro.CarType carType, java.lang.Long speed, java.lang.Long loadVolume, java.lang.Integer quantity, java.lang.CharSequence customerName, com.diploma.avro.OrderStatus status, java.lang.CharSequence deliveryDuration, java.time.Instant deliveryEndTime) {
    this.id = id;
    this.productId = productId;
    this.name = name;
    this.brand = brand;
    this.model = model;
    this.locationId = locationId;
    this.city = city;
    this.country = country;
    this.distanceToWarehouse = distanceToWarehouse;
    this.transportId = transportId;
    this.carType = carType;
    this.speed = speed;
    this.loadVolume = loadVolume;
    this.quantity = quantity;
    this.customerName = customerName;
    this.status = status;
    this.deliveryDuration = deliveryDuration;
    this.deliveryEndTime = deliveryEndTime;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return id;
    case 1: return productId;
    case 2: return name;
    case 3: return brand;
    case 4: return model;
    case 5: return locationId;
    case 6: return city;
    case 7: return country;
    case 8: return distanceToWarehouse;
    case 9: return transportId;
    case 10: return carType;
    case 11: return speed;
    case 12: return loadVolume;
    case 13: return quantity;
    case 14: return customerName;
    case 15: return status;
    case 16: return deliveryDuration;
    case 17: return deliveryEndTime;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: id = (java.lang.Long)value$; break;
    case 1: productId = (java.lang.Long)value$; break;
    case 2: name = (java.lang.CharSequence)value$; break;
    case 3: brand = (java.lang.CharSequence)value$; break;
    case 4: model = (java.lang.CharSequence)value$; break;
    case 5: locationId = (java.lang.Long)value$; break;
    case 6: city = (java.lang.CharSequence)value$; break;
    case 7: country = (java.lang.CharSequence)value$; break;
    case 8: distanceToWarehouse = (java.lang.Long)value$; break;
    case 9: transportId = (java.lang.Long)value$; break;
    case 10: carType = (com.diploma.avro.CarType)value$; break;
    case 11: speed = (java.lang.Long)value$; break;
    case 12: loadVolume = (java.lang.Long)value$; break;
    case 13: quantity = (java.lang.Integer)value$; break;
    case 14: customerName = (java.lang.CharSequence)value$; break;
    case 15: status = (com.diploma.avro.OrderStatus)value$; break;
    case 16: deliveryDuration = (java.lang.CharSequence)value$; break;
    case 17: deliveryEndTime = (java.time.Instant)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'id' field.
   * @return The value of the 'id' field.
   */
  public java.lang.Long getId() {
    return id;
  }


  /**
   * Sets the value of the 'id' field.
   * @param value the value to set.
   */
  public void setId(java.lang.Long value) {
    this.id = value;
  }

  /**
   * Gets the value of the 'productId' field.
   * @return The value of the 'productId' field.
   */
  public java.lang.Long getProductId() {
    return productId;
  }


  /**
   * Sets the value of the 'productId' field.
   * @param value the value to set.
   */
  public void setProductId(java.lang.Long value) {
    this.productId = value;
  }

  /**
   * Gets the value of the 'name' field.
   * @return The value of the 'name' field.
   */
  public java.lang.CharSequence getName() {
    return name;
  }


  /**
   * Sets the value of the 'name' field.
   * @param value the value to set.
   */
  public void setName(java.lang.CharSequence value) {
    this.name = value;
  }

  /**
   * Gets the value of the 'brand' field.
   * @return The value of the 'brand' field.
   */
  public java.lang.CharSequence getBrand() {
    return brand;
  }


  /**
   * Sets the value of the 'brand' field.
   * @param value the value to set.
   */
  public void setBrand(java.lang.CharSequence value) {
    this.brand = value;
  }

  /**
   * Gets the value of the 'model' field.
   * @return The value of the 'model' field.
   */
  public java.lang.CharSequence getModel() {
    return model;
  }


  /**
   * Sets the value of the 'model' field.
   * @param value the value to set.
   */
  public void setModel(java.lang.CharSequence value) {
    this.model = value;
  }

  /**
   * Gets the value of the 'locationId' field.
   * @return The value of the 'locationId' field.
   */
  public java.lang.Long getLocationId() {
    return locationId;
  }


  /**
   * Sets the value of the 'locationId' field.
   * @param value the value to set.
   */
  public void setLocationId(java.lang.Long value) {
    this.locationId = value;
  }

  /**
   * Gets the value of the 'city' field.
   * @return The value of the 'city' field.
   */
  public java.lang.CharSequence getCity() {
    return city;
  }


  /**
   * Sets the value of the 'city' field.
   * @param value the value to set.
   */
  public void setCity(java.lang.CharSequence value) {
    this.city = value;
  }

  /**
   * Gets the value of the 'country' field.
   * @return The value of the 'country' field.
   */
  public java.lang.CharSequence getCountry() {
    return country;
  }


  /**
   * Sets the value of the 'country' field.
   * @param value the value to set.
   */
  public void setCountry(java.lang.CharSequence value) {
    this.country = value;
  }

  /**
   * Gets the value of the 'distanceToWarehouse' field.
   * @return The value of the 'distanceToWarehouse' field.
   */
  public java.lang.Long getDistanceToWarehouse() {
    return distanceToWarehouse;
  }


  /**
   * Sets the value of the 'distanceToWarehouse' field.
   * @param value the value to set.
   */
  public void setDistanceToWarehouse(java.lang.Long value) {
    this.distanceToWarehouse = value;
  }

  /**
   * Gets the value of the 'transportId' field.
   * @return The value of the 'transportId' field.
   */
  public java.lang.Long getTransportId() {
    return transportId;
  }


  /**
   * Sets the value of the 'transportId' field.
   * @param value the value to set.
   */
  public void setTransportId(java.lang.Long value) {
    this.transportId = value;
  }

  /**
   * Gets the value of the 'carType' field.
   * @return The value of the 'carType' field.
   */
  public com.diploma.avro.CarType getCarType() {
    return carType;
  }


  /**
   * Sets the value of the 'carType' field.
   * @param value the value to set.
   */
  public void setCarType(com.diploma.avro.CarType value) {
    this.carType = value;
  }

  /**
   * Gets the value of the 'speed' field.
   * @return The value of the 'speed' field.
   */
  public java.lang.Long getSpeed() {
    return speed;
  }


  /**
   * Sets the value of the 'speed' field.
   * @param value the value to set.
   */
  public void setSpeed(java.lang.Long value) {
    this.speed = value;
  }

  /**
   * Gets the value of the 'loadVolume' field.
   * @return The value of the 'loadVolume' field.
   */
  public java.lang.Long getLoadVolume() {
    return loadVolume;
  }


  /**
   * Sets the value of the 'loadVolume' field.
   * @param value the value to set.
   */
  public void setLoadVolume(java.lang.Long value) {
    this.loadVolume = value;
  }

  /**
   * Gets the value of the 'quantity' field.
   * @return The value of the 'quantity' field.
   */
  public java.lang.Integer getQuantity() {
    return quantity;
  }


  /**
   * Sets the value of the 'quantity' field.
   * @param value the value to set.
   */
  public void setQuantity(java.lang.Integer value) {
    this.quantity = value;
  }

  /**
   * Gets the value of the 'customerName' field.
   * @return The value of the 'customerName' field.
   */
  public java.lang.CharSequence getCustomerName() {
    return customerName;
  }


  /**
   * Sets the value of the 'customerName' field.
   * @param value the value to set.
   */
  public void setCustomerName(java.lang.CharSequence value) {
    this.customerName = value;
  }

  /**
   * Gets the value of the 'status' field.
   * @return The value of the 'status' field.
   */
  public com.diploma.avro.OrderStatus getStatus() {
    return status;
  }


  /**
   * Sets the value of the 'status' field.
   * @param value the value to set.
   */
  public void setStatus(com.diploma.avro.OrderStatus value) {
    this.status = value;
  }

  /**
   * Gets the value of the 'deliveryDuration' field.
   * @return The value of the 'deliveryDuration' field.
   */
  public java.lang.CharSequence getDeliveryDuration() {
    return deliveryDuration;
  }


  /**
   * Sets the value of the 'deliveryDuration' field.
   * @param value the value to set.
   */
  public void setDeliveryDuration(java.lang.CharSequence value) {
    this.deliveryDuration = value;
  }

  /**
   * Gets the value of the 'deliveryEndTime' field.
   * @return The value of the 'deliveryEndTime' field.
   */
  public java.time.Instant getDeliveryEndTime() {
    return deliveryEndTime;
  }


  /**
   * Sets the value of the 'deliveryEndTime' field.
   * @param value the value to set.
   */
  public void setDeliveryEndTime(java.time.Instant value) {
    this.deliveryEndTime = value;
  }

  /**
   * Creates a new LogisticsDTO RecordBuilder.
   * @return A new LogisticsDTO RecordBuilder
   */
  public static com.diploma.avro.LogisticsDTO.Builder newBuilder() {
    return new com.diploma.avro.LogisticsDTO.Builder();
  }

  /**
   * Creates a new LogisticsDTO RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogisticsDTO RecordBuilder
   */
  public static com.diploma.avro.LogisticsDTO.Builder newBuilder(com.diploma.avro.LogisticsDTO.Builder other) {
    if (other == null) {
      return new com.diploma.avro.LogisticsDTO.Builder();
    } else {
      return new com.diploma.avro.LogisticsDTO.Builder(other);
    }
  }

  /**
   * Creates a new LogisticsDTO RecordBuilder by copying an existing LogisticsDTO instance.
   * @param other The existing instance to copy.
   * @return A new LogisticsDTO RecordBuilder
   */
  public static com.diploma.avro.LogisticsDTO.Builder newBuilder(com.diploma.avro.LogisticsDTO other) {
    if (other == null) {
      return new com.diploma.avro.LogisticsDTO.Builder();
    } else {
      return new com.diploma.avro.LogisticsDTO.Builder(other);
    }
  }

  /**
   * RecordBuilder for LogisticsDTO instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogisticsDTO>
    implements org.apache.avro.data.RecordBuilder<LogisticsDTO> {

    private java.lang.Long id;
    private java.lang.Long productId;
    private java.lang.CharSequence name;
    private java.lang.CharSequence brand;
    private java.lang.CharSequence model;
    private java.lang.Long locationId;
    private java.lang.CharSequence city;
    private java.lang.CharSequence country;
    private java.lang.Long distanceToWarehouse;
    private java.lang.Long transportId;
    private com.diploma.avro.CarType carType;
    private java.lang.Long speed;
    private java.lang.Long loadVolume;
    private java.lang.Integer quantity;
    private java.lang.CharSequence customerName;
    private com.diploma.avro.OrderStatus status;
    private java.lang.CharSequence deliveryDuration;
    private java.time.Instant deliveryEndTime;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diploma.avro.LogisticsDTO.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.model)) {
        this.model = data().deepCopy(fields()[4].schema(), other.model);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.city)) {
        this.city = data().deepCopy(fields()[6].schema(), other.city);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.country)) {
        this.country = data().deepCopy(fields()[7].schema(), other.country);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.distanceToWarehouse)) {
        this.distanceToWarehouse = data().deepCopy(fields()[8].schema(), other.distanceToWarehouse);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.transportId)) {
        this.transportId = data().deepCopy(fields()[9].schema(), other.transportId);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.carType)) {
        this.carType = data().deepCopy(fields()[10].schema(), other.carType);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.speed)) {
        this.speed = data().deepCopy(fields()[11].schema(), other.speed);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.loadVolume)) {
        this.loadVolume = data().deepCopy(fields()[12].schema(), other.loadVolume);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.quantity)) {
        this.quantity = data().deepCopy(fields()[13].schema(), other.quantity);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.customerName)) {
        this.customerName = data().deepCopy(fields()[14].schema(), other.customerName);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.status)) {
        this.status = data().deepCopy(fields()[15].schema(), other.status);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.deliveryDuration)) {
        this.deliveryDuration = data().deepCopy(fields()[16].schema(), other.deliveryDuration);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.deliveryEndTime)) {
        this.deliveryEndTime = data().deepCopy(fields()[17].schema(), other.deliveryEndTime);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
    }

    /**
     * Creates a Builder by copying an existing LogisticsDTO instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diploma.avro.LogisticsDTO other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.id)) {
        this.id = data().deepCopy(fields()[0].schema(), other.id);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.productId)) {
        this.productId = data().deepCopy(fields()[1].schema(), other.productId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.name)) {
        this.name = data().deepCopy(fields()[2].schema(), other.name);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.brand)) {
        this.brand = data().deepCopy(fields()[3].schema(), other.brand);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.model)) {
        this.model = data().deepCopy(fields()[4].schema(), other.model);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.locationId)) {
        this.locationId = data().deepCopy(fields()[5].schema(), other.locationId);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.city)) {
        this.city = data().deepCopy(fields()[6].schema(), other.city);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.country)) {
        this.country = data().deepCopy(fields()[7].schema(), other.country);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.distanceToWarehouse)) {
        this.distanceToWarehouse = data().deepCopy(fields()[8].schema(), other.distanceToWarehouse);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.transportId)) {
        this.transportId = data().deepCopy(fields()[9].schema(), other.transportId);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.carType)) {
        this.carType = data().deepCopy(fields()[10].schema(), other.carType);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.speed)) {
        this.speed = data().deepCopy(fields()[11].schema(), other.speed);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.loadVolume)) {
        this.loadVolume = data().deepCopy(fields()[12].schema(), other.loadVolume);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.quantity)) {
        this.quantity = data().deepCopy(fields()[13].schema(), other.quantity);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.customerName)) {
        this.customerName = data().deepCopy(fields()[14].schema(), other.customerName);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.status)) {
        this.status = data().deepCopy(fields()[15].schema(), other.status);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.deliveryDuration)) {
        this.deliveryDuration = data().deepCopy(fields()[16].schema(), other.deliveryDuration);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.deliveryEndTime)) {
        this.deliveryEndTime = data().deepCopy(fields()[17].schema(), other.deliveryEndTime);
        fieldSetFlags()[17] = true;
      }
    }

    /**
      * Gets the value of the 'id' field.
      * @return The value.
      */
    public java.lang.Long getId() {
      return id;
    }


    /**
      * Sets the value of the 'id' field.
      * @param value The value of 'id'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setId(java.lang.Long value) {
      validate(fields()[0], value);
      this.id = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'id' field has been set.
      * @return True if the 'id' field has been set, false otherwise.
      */
    public boolean hasId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'id' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearId() {
      id = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'productId' field.
      * @return The value.
      */
    public java.lang.Long getProductId() {
      return productId;
    }


    /**
      * Sets the value of the 'productId' field.
      * @param value The value of 'productId'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setProductId(java.lang.Long value) {
      validate(fields()[1], value);
      this.productId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'productId' field has been set.
      * @return True if the 'productId' field has been set, false otherwise.
      */
    public boolean hasProductId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'productId' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearProductId() {
      productId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'name' field.
      * @return The value.
      */
    public java.lang.CharSequence getName() {
      return name;
    }


    /**
      * Sets the value of the 'name' field.
      * @param value The value of 'name'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setName(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.name = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'name' field has been set.
      * @return True if the 'name' field has been set, false otherwise.
      */
    public boolean hasName() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'name' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearName() {
      name = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'brand' field.
      * @return The value.
      */
    public java.lang.CharSequence getBrand() {
      return brand;
    }


    /**
      * Sets the value of the 'brand' field.
      * @param value The value of 'brand'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setBrand(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.brand = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'brand' field has been set.
      * @return True if the 'brand' field has been set, false otherwise.
      */
    public boolean hasBrand() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'brand' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearBrand() {
      brand = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'model' field.
      * @return The value.
      */
    public java.lang.CharSequence getModel() {
      return model;
    }


    /**
      * Sets the value of the 'model' field.
      * @param value The value of 'model'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setModel(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.model = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'model' field has been set.
      * @return True if the 'model' field has been set, false otherwise.
      */
    public boolean hasModel() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'model' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearModel() {
      model = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'locationId' field.
      * @return The value.
      */
    public java.lang.Long getLocationId() {
      return locationId;
    }


    /**
      * Sets the value of the 'locationId' field.
      * @param value The value of 'locationId'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setLocationId(java.lang.Long value) {
      validate(fields()[5], value);
      this.locationId = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'locationId' field has been set.
      * @return True if the 'locationId' field has been set, false otherwise.
      */
    public boolean hasLocationId() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'locationId' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearLocationId() {
      locationId = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'city' field.
      * @return The value.
      */
    public java.lang.CharSequence getCity() {
      return city;
    }


    /**
      * Sets the value of the 'city' field.
      * @param value The value of 'city'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setCity(java.lang.CharSequence value) {
      validate(fields()[6], value);
      this.city = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'city' field has been set.
      * @return True if the 'city' field has been set, false otherwise.
      */
    public boolean hasCity() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'city' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearCity() {
      city = null;
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'country' field.
      * @return The value.
      */
    public java.lang.CharSequence getCountry() {
      return country;
    }


    /**
      * Sets the value of the 'country' field.
      * @param value The value of 'country'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setCountry(java.lang.CharSequence value) {
      validate(fields()[7], value);
      this.country = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'country' field has been set.
      * @return True if the 'country' field has been set, false otherwise.
      */
    public boolean hasCountry() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'country' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearCountry() {
      country = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'distanceToWarehouse' field.
      * @return The value.
      */
    public java.lang.Long getDistanceToWarehouse() {
      return distanceToWarehouse;
    }


    /**
      * Sets the value of the 'distanceToWarehouse' field.
      * @param value The value of 'distanceToWarehouse'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setDistanceToWarehouse(java.lang.Long value) {
      validate(fields()[8], value);
      this.distanceToWarehouse = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'distanceToWarehouse' field has been set.
      * @return True if the 'distanceToWarehouse' field has been set, false otherwise.
      */
    public boolean hasDistanceToWarehouse() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'distanceToWarehouse' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearDistanceToWarehouse() {
      distanceToWarehouse = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'transportId' field.
      * @return The value.
      */
    public java.lang.Long getTransportId() {
      return transportId;
    }


    /**
      * Sets the value of the 'transportId' field.
      * @param value The value of 'transportId'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setTransportId(java.lang.Long value) {
      validate(fields()[9], value);
      this.transportId = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'transportId' field has been set.
      * @return True if the 'transportId' field has been set, false otherwise.
      */
    public boolean hasTransportId() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'transportId' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearTransportId() {
      transportId = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'carType' field.
      * @return The value.
      */
    public com.diploma.avro.CarType getCarType() {
      return carType;
    }


    /**
      * Sets the value of the 'carType' field.
      * @param value The value of 'carType'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setCarType(com.diploma.avro.CarType value) {
      validate(fields()[10], value);
      this.carType = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'carType' field has been set.
      * @return True if the 'carType' field has been set, false otherwise.
      */
    public boolean hasCarType() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'carType' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearCarType() {
      carType = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'speed' field.
      * @return The value.
      */
    public java.lang.Long getSpeed() {
      return speed;
    }


    /**
      * Sets the value of the 'speed' field.
      * @param value The value of 'speed'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setSpeed(java.lang.Long value) {
      validate(fields()[11], value);
      this.speed = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'speed' field has been set.
      * @return True if the 'speed' field has been set, false otherwise.
      */
    public boolean hasSpeed() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'speed' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearSpeed() {
      speed = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'loadVolume' field.
      * @return The value.
      */
    public java.lang.Long getLoadVolume() {
      return loadVolume;
    }


    /**
      * Sets the value of the 'loadVolume' field.
      * @param value The value of 'loadVolume'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setLoadVolume(java.lang.Long value) {
      validate(fields()[12], value);
      this.loadVolume = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'loadVolume' field has been set.
      * @return True if the 'loadVolume' field has been set, false otherwise.
      */
    public boolean hasLoadVolume() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'loadVolume' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearLoadVolume() {
      loadVolume = null;
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'quantity' field.
      * @return The value.
      */
    public java.lang.Integer getQuantity() {
      return quantity;
    }


    /**
      * Sets the value of the 'quantity' field.
      * @param value The value of 'quantity'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setQuantity(java.lang.Integer value) {
      validate(fields()[13], value);
      this.quantity = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'quantity' field has been set.
      * @return True if the 'quantity' field has been set, false otherwise.
      */
    public boolean hasQuantity() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'quantity' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearQuantity() {
      quantity = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'customerName' field.
      * @return The value.
      */
    public java.lang.CharSequence getCustomerName() {
      return customerName;
    }


    /**
      * Sets the value of the 'customerName' field.
      * @param value The value of 'customerName'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setCustomerName(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.customerName = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'customerName' field has been set.
      * @return True if the 'customerName' field has been set, false otherwise.
      */
    public boolean hasCustomerName() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'customerName' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearCustomerName() {
      customerName = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'status' field.
      * @return The value.
      */
    public com.diploma.avro.OrderStatus getStatus() {
      return status;
    }


    /**
      * Sets the value of the 'status' field.
      * @param value The value of 'status'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setStatus(com.diploma.avro.OrderStatus value) {
      validate(fields()[15], value);
      this.status = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'status' field has been set.
      * @return True if the 'status' field has been set, false otherwise.
      */
    public boolean hasStatus() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'status' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearStatus() {
      status = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryDuration' field.
      * @return The value.
      */
    public java.lang.CharSequence getDeliveryDuration() {
      return deliveryDuration;
    }


    /**
      * Sets the value of the 'deliveryDuration' field.
      * @param value The value of 'deliveryDuration'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setDeliveryDuration(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.deliveryDuration = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryDuration' field has been set.
      * @return True if the 'deliveryDuration' field has been set, false otherwise.
      */
    public boolean hasDeliveryDuration() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'deliveryDuration' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearDeliveryDuration() {
      deliveryDuration = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'deliveryEndTime' field.
      * @return The value.
      */
    public java.time.Instant getDeliveryEndTime() {
      return deliveryEndTime;
    }


    /**
      * Sets the value of the 'deliveryEndTime' field.
      * @param value The value of 'deliveryEndTime'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder setDeliveryEndTime(java.time.Instant value) {
      validate(fields()[17], value);
      this.deliveryEndTime = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'deliveryEndTime' field has been set.
      * @return True if the 'deliveryEndTime' field has been set, false otherwise.
      */
    public boolean hasDeliveryEndTime() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'deliveryEndTime' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsDTO.Builder clearDeliveryEndTime() {
      deliveryEndTime = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogisticsDTO build() {
      try {
        LogisticsDTO record = new LogisticsDTO();
        record.id = fieldSetFlags()[0] ? this.id : (java.lang.Long) defaultValue(fields()[0]);
        record.productId = fieldSetFlags()[1] ? this.productId : (java.lang.Long) defaultValue(fields()[1]);
        record.name = fieldSetFlags()[2] ? this.name : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.brand = fieldSetFlags()[3] ? this.brand : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.model = fieldSetFlags()[4] ? this.model : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.locationId = fieldSetFlags()[5] ? this.locationId : (java.lang.Long) defaultValue(fields()[5]);
        record.city = fieldSetFlags()[6] ? this.city : (java.lang.CharSequence) defaultValue(fields()[6]);
        record.country = fieldSetFlags()[7] ? this.country : (java.lang.CharSequence) defaultValue(fields()[7]);
        record.distanceToWarehouse = fieldSetFlags()[8] ? this.distanceToWarehouse : (java.lang.Long) defaultValue(fields()[8]);
        record.transportId = fieldSetFlags()[9] ? this.transportId : (java.lang.Long) defaultValue(fields()[9]);
        record.carType = fieldSetFlags()[10] ? this.carType : (com.diploma.avro.CarType) defaultValue(fields()[10]);
        record.speed = fieldSetFlags()[11] ? this.speed : (java.lang.Long) defaultValue(fields()[11]);
        record.loadVolume = fieldSetFlags()[12] ? this.loadVolume : (java.lang.Long) defaultValue(fields()[12]);
        record.quantity = fieldSetFlags()[13] ? this.quantity : (java.lang.Integer) defaultValue(fields()[13]);
        record.customerName = fieldSetFlags()[14] ? this.customerName : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.status = fieldSetFlags()[15] ? this.status : (com.diploma.avro.OrderStatus) defaultValue(fields()[15]);
        record.deliveryDuration = fieldSetFlags()[16] ? this.deliveryDuration : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.deliveryEndTime = fieldSetFlags()[17] ? this.deliveryEndTime : (java.time.Instant) defaultValue(fields()[17]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogisticsDTO>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogisticsDTO>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogisticsDTO>
    READER$ = (org.apache.avro.io.DatumReader<LogisticsDTO>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

}










