/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diploma.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class LogisticsListWrapper extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 5203553837062577780L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"LogisticsListWrapper\",\"namespace\":\"com.diploma.avro\",\"fields\":[{\"name\":\"logistics\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"LogisticsDTO\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"productId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"name\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"brand\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"model\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"locationId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"city\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"country\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"distanceToWarehouse\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"transportId\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"carType\",\"type\":[\"null\",{\"type\":\"enum\",\"name\":\"CarType\",\"symbols\":[\"CADDY\",\"CARGOVAN\",\"TRUCK\",\"TRAIN\"]}],\"default\":null},{\"name\":\"speed\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"loadVolume\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"quantity\",\"type\":[\"null\",\"int\"],\"default\":null},{\"name\":\"customerName\",\"type\":[\"null\",\"string\"],\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"OPEN\",\"IN_PRODUCTION\",\"DELIVERY\",\"DELIVERED\",\"SOLD\",\"RETURNED\"]}},{\"name\":\"deliveryDuration\",\"type\":[\"null\",\"string\"],\"default\":null}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<LogisticsListWrapper> ENCODER =
      new BinaryMessageEncoder<LogisticsListWrapper>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<LogisticsListWrapper> DECODER =
      new BinaryMessageDecoder<LogisticsListWrapper>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<LogisticsListWrapper> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<LogisticsListWrapper> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<LogisticsListWrapper> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<LogisticsListWrapper>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this LogisticsListWrapper to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a LogisticsListWrapper from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a LogisticsListWrapper instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static LogisticsListWrapper fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<com.diploma.avro.LogisticsDTO> logistics;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public LogisticsListWrapper() {}

  /**
   * All-args constructor.
   * @param logistics The new value for logistics
   */
  public LogisticsListWrapper(java.util.List<com.diploma.avro.LogisticsDTO> logistics) {
    this.logistics = logistics;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return logistics;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: logistics = (java.util.List<com.diploma.avro.LogisticsDTO>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'logistics' field.
   * @return The value of the 'logistics' field.
   */
  public java.util.List<com.diploma.avro.LogisticsDTO> getLogistics() {
    return logistics;
  }


  /**
   * Sets the value of the 'logistics' field.
   * @param value the value to set.
   */
  public void setLogistics(java.util.List<com.diploma.avro.LogisticsDTO> value) {
    this.logistics = value;
  }

  /**
   * Creates a new LogisticsListWrapper RecordBuilder.
   * @return A new LogisticsListWrapper RecordBuilder
   */
  public static com.diploma.avro.LogisticsListWrapper.Builder newBuilder() {
    return new com.diploma.avro.LogisticsListWrapper.Builder();
  }

  /**
   * Creates a new LogisticsListWrapper RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new LogisticsListWrapper RecordBuilder
   */
  public static com.diploma.avro.LogisticsListWrapper.Builder newBuilder(com.diploma.avro.LogisticsListWrapper.Builder other) {
    if (other == null) {
      return new com.diploma.avro.LogisticsListWrapper.Builder();
    } else {
      return new com.diploma.avro.LogisticsListWrapper.Builder(other);
    }
  }

  /**
   * Creates a new LogisticsListWrapper RecordBuilder by copying an existing LogisticsListWrapper instance.
   * @param other The existing instance to copy.
   * @return A new LogisticsListWrapper RecordBuilder
   */
  public static com.diploma.avro.LogisticsListWrapper.Builder newBuilder(com.diploma.avro.LogisticsListWrapper other) {
    if (other == null) {
      return new com.diploma.avro.LogisticsListWrapper.Builder();
    } else {
      return new com.diploma.avro.LogisticsListWrapper.Builder(other);
    }
  }

  /**
   * RecordBuilder for LogisticsListWrapper instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<LogisticsListWrapper>
    implements org.apache.avro.data.RecordBuilder<LogisticsListWrapper> {

    private java.util.List<com.diploma.avro.LogisticsDTO> logistics;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diploma.avro.LogisticsListWrapper.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.logistics)) {
        this.logistics = data().deepCopy(fields()[0].schema(), other.logistics);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing LogisticsListWrapper instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diploma.avro.LogisticsListWrapper other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.logistics)) {
        this.logistics = data().deepCopy(fields()[0].schema(), other.logistics);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'logistics' field.
      * @return The value.
      */
    public java.util.List<com.diploma.avro.LogisticsDTO> getLogistics() {
      return logistics;
    }


    /**
      * Sets the value of the 'logistics' field.
      * @param value The value of 'logistics'.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsListWrapper.Builder setLogistics(java.util.List<com.diploma.avro.LogisticsDTO> value) {
      validate(fields()[0], value);
      this.logistics = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'logistics' field has been set.
      * @return True if the 'logistics' field has been set, false otherwise.
      */
    public boolean hasLogistics() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'logistics' field.
      * @return This builder.
      */
    public com.diploma.avro.LogisticsListWrapper.Builder clearLogistics() {
      logistics = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public LogisticsListWrapper build() {
      try {
        LogisticsListWrapper record = new LogisticsListWrapper();
        record.logistics = fieldSetFlags()[0] ? this.logistics : (java.util.List<com.diploma.avro.LogisticsDTO>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<LogisticsListWrapper>
    WRITER$ = (org.apache.avro.io.DatumWriter<LogisticsListWrapper>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<LogisticsListWrapper>
    READER$ = (org.apache.avro.io.DatumReader<LogisticsListWrapper>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.logistics.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.diploma.avro.LogisticsDTO e0: this.logistics) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.diploma.avro.LogisticsDTO> a0 = this.logistics;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.diploma.avro.LogisticsDTO>((int)size0, SCHEMA$.getField("logistics").schema());
        this.logistics = a0;
      } else a0.clear();
      SpecificData.Array<com.diploma.avro.LogisticsDTO> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.diploma.avro.LogisticsDTO>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.diploma.avro.LogisticsDTO e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.diploma.avro.LogisticsDTO();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.diploma.avro.LogisticsDTO> a0 = this.logistics;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.diploma.avro.LogisticsDTO>((int)size0, SCHEMA$.getField("logistics").schema());
            this.logistics = a0;
          } else a0.clear();
          SpecificData.Array<com.diploma.avro.LogisticsDTO> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.diploma.avro.LogisticsDTO>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.diploma.avro.LogisticsDTO e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.diploma.avro.LogisticsDTO();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










