INSERT INTO location (id, city, country)
VALUES
       (1, 'Lisbon', 'Portugal'),
       (2, 'Andorra la Vella', 'Andorra'),
       (3, 'Stockholm', 'Sweden'),
       (4, 'Helsinki', 'Finland'),
       (5, 'Kyiv', 'Ukraine'),
       (6, 'Monaco', 'Monaco'),
       (7, 'Madrid', 'Spain'),
       (8, 'Warsaw', 'Poland'),
       (9, 'Helsinki', 'Finland'),
       (10, 'Budapest', 'Hungary'),
       (11, 'Paris', 'France'),
       (12, 'Brussels', 'Belgium'),
       (13, 'Vienna', 'Austria'),
       (14, 'Helsinki', 'Finland'),
       (15, 'Paris', 'France'),
       (16, 'Dublin', 'Ireland'),
       (17, 'Riga', 'Latvia'),
       (18, 'Tallinn', 'Estonia'),
       (19, 'Oslo', 'Norway'),
       (20, 'Athens', 'Greece'),
       (21, 'Zagreb', 'Croatia'),
       (22, 'Sarajevo', 'Bosnia and Herzegovina'),
       (23, 'Copenhagen', 'Denmark'),
       (24, 'Belgrade', 'Serbia'),
       (25, 'Ljubljana', 'Slovenia'),
       (26, 'Prague', 'Czech Republic'),
       (27, 'Stockholm', 'Sweden'),
       (28, 'Vilnius', 'Lithuania'),
       (29, 'Warsaw', 'Poland'),
       (30, 'Monaco', 'Monaco');
