/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diploma.avro;
@org.apache.avro.specific.AvroGenerated
public enum CarType implements org.apache.avro.generic.GenericEnumSymbol<CarType> {
  CADDY, CARGOVAN, TRUCK, TRAIN  ;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"enum\",\"name\":\"CarType\",\"namespace\":\"com.diploma.avro\",\"symbols\":[\"CADDY\",\"CARGOVAN\",\"TRUCK\",\"TRAIN\"]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
}
