/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.diploma.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class SalesListWrapper extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6946323361738520759L;
  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SalesListWrapper\",\"namespace\":\"com.diploma.avro\",\"fields\":[{\"name\":\"sales\",\"type\":{\"type\":\"array\",\"items\":{\"type\":\"record\",\"name\":\"SalesDto\",\"fields\":[{\"name\":\"id\",\"type\":[\"null\",\"long\"],\"default\":null},{\"name\":\"status\",\"type\":{\"type\":\"enum\",\"name\":\"OrderStatus\",\"symbols\":[\"OPEN\",\"IN_PRODUCTION\",\"DELIVERY\",\"DELIVERED\",\"SOLD\",\"RETURNED\"]}}]}}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<SalesListWrapper> ENCODER =
      new BinaryMessageEncoder<SalesListWrapper>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<SalesListWrapper> DECODER =
      new BinaryMessageDecoder<SalesListWrapper>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<SalesListWrapper> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<SalesListWrapper> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<SalesListWrapper> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<SalesListWrapper>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this SalesListWrapper to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a SalesListWrapper from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a SalesListWrapper instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static SalesListWrapper fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

   private java.util.List<com.diploma.avro.SalesDto> sales;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public SalesListWrapper() {}

  /**
   * All-args constructor.
   * @param sales The new value for sales
   */
  public SalesListWrapper(java.util.List<com.diploma.avro.SalesDto> sales) {
    this.sales = sales;
  }

  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call.
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return sales;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: sales = (java.util.List<com.diploma.avro.SalesDto>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'sales' field.
   * @return The value of the 'sales' field.
   */
  public java.util.List<com.diploma.avro.SalesDto> getSales() {
    return sales;
  }


  /**
   * Sets the value of the 'sales' field.
   * @param value the value to set.
   */
  public void setSales(java.util.List<com.diploma.avro.SalesDto> value) {
    this.sales = value;
  }

  /**
   * Creates a new SalesListWrapper RecordBuilder.
   * @return A new SalesListWrapper RecordBuilder
   */
  public static com.diploma.avro.SalesListWrapper.Builder newBuilder() {
    return new com.diploma.avro.SalesListWrapper.Builder();
  }

  /**
   * Creates a new SalesListWrapper RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new SalesListWrapper RecordBuilder
   */
  public static com.diploma.avro.SalesListWrapper.Builder newBuilder(com.diploma.avro.SalesListWrapper.Builder other) {
    if (other == null) {
      return new com.diploma.avro.SalesListWrapper.Builder();
    } else {
      return new com.diploma.avro.SalesListWrapper.Builder(other);
    }
  }

  /**
   * Creates a new SalesListWrapper RecordBuilder by copying an existing SalesListWrapper instance.
   * @param other The existing instance to copy.
   * @return A new SalesListWrapper RecordBuilder
   */
  public static com.diploma.avro.SalesListWrapper.Builder newBuilder(com.diploma.avro.SalesListWrapper other) {
    if (other == null) {
      return new com.diploma.avro.SalesListWrapper.Builder();
    } else {
      return new com.diploma.avro.SalesListWrapper.Builder(other);
    }
  }

  /**
   * RecordBuilder for SalesListWrapper instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SalesListWrapper>
    implements org.apache.avro.data.RecordBuilder<SalesListWrapper> {

    private java.util.List<com.diploma.avro.SalesDto> sales;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.diploma.avro.SalesListWrapper.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.sales)) {
        this.sales = data().deepCopy(fields()[0].schema(), other.sales);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
    }

    /**
     * Creates a Builder by copying an existing SalesListWrapper instance
     * @param other The existing instance to copy.
     */
    private Builder(com.diploma.avro.SalesListWrapper other) {
      super(SCHEMA$);
      if (isValidValue(fields()[0], other.sales)) {
        this.sales = data().deepCopy(fields()[0].schema(), other.sales);
        fieldSetFlags()[0] = true;
      }
    }

    /**
      * Gets the value of the 'sales' field.
      * @return The value.
      */
    public java.util.List<com.diploma.avro.SalesDto> getSales() {
      return sales;
    }


    /**
      * Sets the value of the 'sales' field.
      * @param value The value of 'sales'.
      * @return This builder.
      */
    public com.diploma.avro.SalesListWrapper.Builder setSales(java.util.List<com.diploma.avro.SalesDto> value) {
      validate(fields()[0], value);
      this.sales = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'sales' field has been set.
      * @return True if the 'sales' field has been set, false otherwise.
      */
    public boolean hasSales() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'sales' field.
      * @return This builder.
      */
    public com.diploma.avro.SalesListWrapper.Builder clearSales() {
      sales = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public SalesListWrapper build() {
      try {
        SalesListWrapper record = new SalesListWrapper();
        record.sales = fieldSetFlags()[0] ? this.sales : (java.util.List<com.diploma.avro.SalesDto>) defaultValue(fields()[0]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<SalesListWrapper>
    WRITER$ = (org.apache.avro.io.DatumWriter<SalesListWrapper>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<SalesListWrapper>
    READER$ = (org.apache.avro.io.DatumReader<SalesListWrapper>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    long size0 = this.sales.size();
    out.writeArrayStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (com.diploma.avro.SalesDto e0: this.sales) {
      actualSize0++;
      out.startItem();
      e0.customEncode(out);
    }
    out.writeArrayEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Array-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      long size0 = in.readArrayStart();
      java.util.List<com.diploma.avro.SalesDto> a0 = this.sales;
      if (a0 == null) {
        a0 = new SpecificData.Array<com.diploma.avro.SalesDto>((int)size0, SCHEMA$.getField("sales").schema());
        this.sales = a0;
      } else a0.clear();
      SpecificData.Array<com.diploma.avro.SalesDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.diploma.avro.SalesDto>)a0 : null);
      for ( ; 0 < size0; size0 = in.arrayNext()) {
        for ( ; size0 != 0; size0--) {
          com.diploma.avro.SalesDto e0 = (ga0 != null ? ga0.peek() : null);
          if (e0 == null) {
            e0 = new com.diploma.avro.SalesDto();
          }
          e0.customDecode(in);
          a0.add(e0);
        }
      }

    } else {
      for (int i = 0; i < 1; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          long size0 = in.readArrayStart();
          java.util.List<com.diploma.avro.SalesDto> a0 = this.sales;
          if (a0 == null) {
            a0 = new SpecificData.Array<com.diploma.avro.SalesDto>((int)size0, SCHEMA$.getField("sales").schema());
            this.sales = a0;
          } else a0.clear();
          SpecificData.Array<com.diploma.avro.SalesDto> ga0 = (a0 instanceof SpecificData.Array ? (SpecificData.Array<com.diploma.avro.SalesDto>)a0 : null);
          for ( ; 0 < size0; size0 = in.arrayNext()) {
            for ( ; size0 != 0; size0--) {
              com.diploma.avro.SalesDto e0 = (ga0 != null ? ga0.peek() : null);
              if (e0 == null) {
                e0 = new com.diploma.avro.SalesDto();
              }
              e0.customDecode(in);
              a0.add(e0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










