INSERT INTO location (id, city, country, distance_to_warehouse) VALUES
                                             (1, 'Lisbon', 'Portugal',3194),
                                             (2, 'Andorra la Vella', 'Andorra',2203),
                                             (3, 'Stockholm', 'Sweden',1540),
                                             (4, 'Helsinki', 'Finland',1483),
                                             (5, 'Kyiv', 'Ukraine',400),
                                             (6, 'Monaco', 'Monaco',1705),
                                             (7, 'Madrid', 'Spain',2694),
                                             (8, 'Warsaw', 'Poland',804),
                                             (9, 'Helsinki', 'Finland',1483),
                                             (10, 'Budapest', 'Hungary',732),
                                             (11, 'Paris', 'France',1975),
                                             (12, 'Brussels', 'Belgium',1828),
                                             (13, 'Vienna', 'Austria',942),
                                             (14, 'Helsinki', 'Finland',1483),
                                             (15, 'Paris', 'France',1975),
                                             (16, 'Dublin', 'Ireland',2566),
                                             (17, 'Riga', 'Latvia',1149),
                                             (18, 'Tallinn', 'Estonia',1406),
                                             (19, 'Oslo', 'Norway',1855),
                                             (20, 'Athens', 'Greece',875),
                                             (21, 'Zagreb', 'Croatia',993),
                                             (22, 'Sarajevo', 'Bosnia and Herzegovina',887),
                                             (23, 'Copenhagen', 'Denmark',1477),
                                             (24, 'Belgrade', 'Serbia',692),
                                             (25, 'Ljubljana', 'Slovenia',1099),
                                             (26, 'Prague', 'Czech Republic',1111),
                                             (27, 'Stockholm', 'Sweden',1540),
                                             (28, 'Vilnius', 'Lithuania',887),
                                             (29, 'Warsaw', 'Poland',804),
                                             (30, 'Monaco', 'Monaco',1705);
